#!/usr/bin/env python3
"""Deterministic fixed-point LMS step-size sweep.

Uses the same Q1.15 arithmetic, LFSR stimulus, and hidden 2-tap path as the RTL
self-checking testbench. No third-party Python packages are required.
"""

from __future__ import annotations

import argparse
import csv
import math
from dataclasses import dataclass
from pathlib import Path

NSAMPLES = 3000
HIDDEN_TAPS = (16384, -8192, 0, 0)  # +0.5, -0.25, 0, 0 in Q1.15
MU_SHIFTS = (3, 4, 5, 6)            # mu = 1/8, 1/16, 1/32, 1/64


def sat16(value: int) -> int:
    return max(-32768, min(32767, int(value)))


def signed16(value: int) -> int:
    value &= 0xFFFF
    return value - 0x10000 if value & 0x8000 else value


def stimulus(count: int):
    lfsr = 0xACE1
    for _ in range(count):
        feedback = ((lfsr >> 15) ^ (lfsr >> 13) ^ (lfsr >> 12) ^ (lfsr >> 10)) & 1
        lfsr = ((lfsr << 1) & 0xFFFF) | feedback
        yield signed16(lfsr) >> 1


@dataclass
class SweepResult:
    mu_shift: int
    early_mse: int
    late_mse: int
    reduction_db: float
    coeff0: int
    coeff1: int
    coeff2: int
    coeff3: int
    coefficient_l1_error: int

    @property
    def mu_text(self) -> str:
        return f"1/{1 << self.mu_shift}"


def run_case(mu_shift: int) -> SweepResult:
    weights = [0, 0, 0, 0]
    x1 = x2 = x3 = 0
    previous_x = 0
    error_power = []

    for x in stimulus(NSAMPLES):
        desired_acc = x * HIDDEN_TAPS[0] + previous_x * HIDDEN_TAPS[1]
        desired = desired_acc >> 15

        estimate_acc = x * weights[0] + x1 * weights[1] + x2 * weights[2] + x3 * weights[3]
        estimate = sat16(estimate_acc >> 15)
        error = sat16(desired - estimate)

        taps = (x, x1, x2, x3)
        update_shift = 15 + mu_shift
        for index, tap in enumerate(taps):
            delta = (error * tap) >> update_shift
            weights[index] = sat16(weights[index] + delta)

        error_power.append(error * error)
        x3, x2, x1 = x2, x1, x
        previous_x = x

    early_mse = sum(error_power[100:600]) // 500
    late_mse = sum(error_power[2500:3000]) // 500
    reduction_db = 10.0 * math.log10(early_mse / late_mse)
    l1_error = sum(abs(weights[i] - HIDDEN_TAPS[i]) for i in range(4))

    return SweepResult(
        mu_shift=mu_shift,
        early_mse=early_mse,
        late_mse=late_mse,
        reduction_db=reduction_db,
        coeff0=weights[0],
        coeff1=weights[1],
        coeff2=weights[2],
        coeff3=weights[3],
        coefficient_l1_error=l1_error,
    )


def write_csv(results, path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow([
            "mu_shift", "mu", "early_mse", "late_mse", "mse_reduction_db",
            "coeff0", "coeff1", "coeff2", "coeff3", "coefficient_l1_error"
        ])
        for r in results:
            writer.writerow([
                r.mu_shift, r.mu_text, r.early_mse, r.late_mse,
                f"{r.reduction_db:.3f}", r.coeff0, r.coeff1,
                r.coeff2, r.coeff3, r.coefficient_l1_error
            ])


def write_markdown(results, path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# LMS step-size sweep",
        "",
        "This experiment uses the same deterministic Q1.15 stimulus and hidden path as the RTL testbench,",
        "but sweeps the LMS step size to show the convergence tradeoff.",
        "",
        "Hidden path: `[+0.5, -0.25, 0, 0]` = `[16384, -8192, 0, 0]` in Q1.15.",
        "",
        "| mu | early MSE | late MSE | reduction | final Q1.15 coefficients | coefficient L1 error |",
        "|---:|---:|---:|---:|---|---:|",
    ]
    for r in results:
        coeffs = f"[{r.coeff0}, {r.coeff1}, {r.coeff2}, {r.coeff3}]"
        lines.append(
            f"| {r.mu_text} | {r.early_mse} | {r.late_mse} | {r.reduction_db:.2f} dB | `{coeffs}` | {r.coefficient_l1_error} |"
        )
    lines += [
        "",
        "## What this shows",
        "",
        "- Larger `mu` adapts faster, so its error becomes small earlier in the run.",
        "- Smaller `mu` adapts more slowly; after only 3000 samples it still has more coefficient error.",
        "- In this particular deterministic run, `mu = 1/16` gives the largest early-to-late MSE reduction,",
        "  while `mu = 1/8` finishes closest to the hidden coefficients and with the lowest late-window MSE.",
        "- This is a step-size sensitivity experiment, not a universal claim that one `mu` is always best.",
        "  Stability and convergence depend on reference-signal power, correlation, filter length and fixed-point scaling.",
        "",
        "The CSV and SVG in this directory are generated by `model/lms_mu_sweep.py`.",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_svg(results, path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)
    width, height = 860, 460
    left, top = 90, 55
    plot_w, plot_h = 700, 310
    logs = [math.log10(r.late_mse) for r in results]
    lo = max(0.0, math.floor(min(logs)) - 0.2)
    hi = math.ceil(max(logs)) + 0.2

    def y_for(value):
        lv = math.log10(value)
        return top + (hi - lv) / (hi - lo) * plot_h

    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        '<rect width="100%" height="100%" fill="white"/>',
        '<text x="430" y="28" text-anchor="middle" font-family="sans-serif" font-size="20">Fixed-point LMS step-size sweep</text>',
        f'<line x1="{left}" y1="{top}" x2="{left}" y2="{top+plot_h}" stroke="black"/>',
        f'<line x1="{left}" y1="{top+plot_h}" x2="{left+plot_w}" y2="{top+plot_h}" stroke="black"/>',
    ]

    tick = math.ceil(lo)
    while tick <= math.floor(hi):
        y = top + (hi - tick) / (hi - lo) * plot_h
        parts.append(f'<line x1="{left}" y1="{y:.1f}" x2="{left+plot_w}" y2="{y:.1f}" stroke="#dddddd"/>')
        parts.append(f'<text x="{left-10}" y="{y+5:.1f}" text-anchor="end" font-family="sans-serif" font-size="12">10^{tick}</text>')
        tick += 1

    step = plot_w / len(results)
    bar_w = 78
    for idx, r in enumerate(results):
        cx = left + step * (idx + 0.5)
        y = y_for(r.late_mse)
        h = top + plot_h - y
        parts.append(f'<rect x="{cx-bar_w/2:.1f}" y="{y:.1f}" width="{bar_w}" height="{h:.1f}" fill="#4c78a8"/>')
        parts.append(f'<text x="{cx:.1f}" y="{top+plot_h+25}" text-anchor="middle" font-family="sans-serif" font-size="13">mu={r.mu_text}</text>')
        parts.append(f'<text x="{cx:.1f}" y="{max(top+14,y-7):.1f}" text-anchor="middle" font-family="sans-serif" font-size="12">{r.late_mse}</text>')

    parts.append(f'<text x="{left+plot_w/2}" y="{height-15}" text-anchor="middle" font-family="sans-serif" font-size="13">LMS step size</text>')
    parts.append(f'<text x="22" y="{top+plot_h/2}" transform="rotate(-90 22 {top+plot_h/2})" text-anchor="middle" font-family="sans-serif" font-size="13">Late-window MSE (log scale)</text>')
    parts.append('</svg>')
    path.write_text("\n".join(parts) + "\n", encoding="utf-8")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", default="results", help="directory for generated artifacts")
    args = parser.parse_args()

    out = Path(args.output_dir)
    results = [run_case(mu_shift) for mu_shift in MU_SHIFTS]

    write_csv(results, out / "mu_sweep.csv")
    write_markdown(results, out / "mu_sweep.md")
    write_svg(results, out / "mu_sweep.svg")

    print("mu       early MSE   late MSE   reduction   final coefficients")
    for r in results:
        print(
            f"{r.mu_text:>5}  {r.early_mse:>11}  {r.late_mse:>9}  "
            f"{r.reduction_db:>8.2f} dB   "
            f"[{r.coeff0}, {r.coeff1}, {r.coeff2}, {r.coeff3}]"
        )


if __name__ == "__main__":
    main()
