`timescale 1ns/1ps

module tb_lms_adaptive_filter;

    reg clk;
    reg rst;
    reg sample_valid;
    reg signed [15:0] reference_in;
    reg signed [15:0] desired_in;

    wire signed [15:0] noise_estimate;
    wire signed [15:0] error_out;
    wire signed [15:0] coeff0;
    wire signed [15:0] coeff1;
    wire signed [15:0] coeff2;
    wire signed [15:0] coeff3;

    reg [15:0] lfsr;
    reg signed [15:0] x_sample;
    reg signed [15:0] x_prev;
    reg signed [15:0] d_sample;
    reg signed [63:0] plant_acc;
    reg signed [31:0] err_tmp;
    reg [63:0] err_sq;
    reg [63:0] early_sum;
    reg [63:0] late_sum;
    reg [63:0] early_avg;
    reg [63:0] late_avg;

    integer n;
    integer early_count;
    integer late_count;
    integer failures;

    // Unknown 2-tap path used by the testbench:
    // h0 = +0.5, h1 = -0.25 in Q1.15.
    localparam signed [15:0] H0 = 16'sd16384;
    localparam signed [15:0] H1 = -16'sd8192;

    lms_adaptive_filter #(
        .MU_SHIFT(4)
    ) dut (
        .clk(clk),
        .rst(rst),
        .sample_valid(sample_valid),
        .reference_in(reference_in),
        .desired_in(desired_in),
        .noise_estimate(noise_estimate),
        .error_out(error_out),
        .coeff0(coeff0),
        .coeff1(coeff1),
        .coeff2(coeff2),
        .coeff3(coeff3)
    );

    always #5 clk = ~clk;

    task drive_sample;
        input signed [15:0] x;
        input signed [15:0] d;
        begin
            @(negedge clk);
            reference_in = x;
            desired_in = d;
            sample_valid = 1'b1;

            @(posedge clk);
            #1;
        end
    endtask

    initial begin
        $dumpfile("build/lms.vcd");
        $dumpvars(0, tb_lms_adaptive_filter);

        clk = 1'b0;
        rst = 1'b1;
        sample_valid = 1'b0;
        reference_in = 16'sd0;
        desired_in = 16'sd0;

        lfsr = 16'hACE1;
        x_sample = 16'sd0;
        x_prev = 16'sd0;
        d_sample = 16'sd0;

        early_sum = 64'd0;
        late_sum = 64'd0;
        early_count = 0;
        late_count = 0;
        failures = 0;

        repeat (4) @(posedge clk);
        rst = 1'b0;

        // Train the adaptive filter on pseudo-random reference samples.
        // desired_in is generated by a hidden 2-tap FIR path. A correct LMS
        // implementation should learn approximately [+0.5, -0.25, 0, 0].
        for (n = 0; n < 3000; n = n + 1) begin
            lfsr = {lfsr[14:0], lfsr[15] ^ lfsr[13] ^ lfsr[12] ^ lfsr[10]};

            // Convert the signed LFSR word to roughly +/-0.5 full scale.
            x_sample = $signed(lfsr) >>> 1;

            // Synthetic unknown noise path: d[n] = 0.5*x[n] - 0.25*x[n-1].
            plant_acc = 64'sd0;
            plant_acc = plant_acc + ($signed(x_sample) * $signed(H0));
            plant_acc = plant_acc + ($signed(x_prev)   * $signed(H1));
            d_sample = $signed(plant_acc) >>> 15;

            drive_sample(x_sample, d_sample);

            err_tmp = $signed(error_out);
            err_sq = $signed(err_tmp) * $signed(err_tmp);

            if ((n >= 100) && (n < 600)) begin
                early_sum = early_sum + err_sq;
                early_count = early_count + 1;
            end

            if ((n >= 2500) && (n < 3000)) begin
                late_sum = late_sum + err_sq;
                late_count = late_count + 1;
            end

            x_prev = x_sample;
        end

        @(negedge clk);
        sample_valid = 1'b0;

        early_avg = early_sum / early_count;
        late_avg = late_sum / late_count;

        $display("------------------------------------------------------------");
        $display("LMS convergence test");
        $display("Early-window mean squared error : %0d", early_avg);
        $display("Late-window mean squared error  : %0d", late_avg);
        $display("Learned coefficients (Q1.15): %0d, %0d, %0d, %0d",
                 coeff0, coeff1, coeff2, coeff3);
        $display("Expected approximately          : 16384, -8192, 0, 0");
        $display("------------------------------------------------------------");

        // Require at least 10x reduction in MSE.
        if (late_avg >= (early_avg / 10)) begin
            $display("FAIL: error power did not fall enough.");
            failures = failures + 1;
        end

        // Loose coefficient tolerances make the test robust to fixed-point noise
        // while still proving that adaptation is happening in the correct direction.
        if ((coeff0 < 16'sd14884) || (coeff0 > 16'sd17884)) begin
            $display("FAIL: coeff0 did not converge near +0.5.");
            failures = failures + 1;
        end

        if ((coeff1 < -16'sd9692) || (coeff1 > -16'sd6692)) begin
            $display("FAIL: coeff1 did not converge near -0.25.");
            failures = failures + 1;
        end

        if ((coeff2 < -16'sd1500) || (coeff2 > 16'sd1500)) begin
            $display("FAIL: coeff2 should remain near zero.");
            failures = failures + 1;
        end

        if ((coeff3 < -16'sd1500) || (coeff3 > 16'sd1500)) begin
            $display("FAIL: coeff3 should remain near zero.");
            failures = failures + 1;
        end

        if (failures == 0) begin
            $display("PASS: LMS adaptation and convergence verified.");
            $finish;
        end else begin
            $display("TEST FAILED with %0d failure(s).", failures);
            $fatal(1);
        end
    end

endmodule
